### ISSUE TITLE
Match Version to twitter ecosystem

### ISSUE THREAD

**Issue by chris-vale-ck** [travisbrown/iteratee-twitter#5]
Having catbirds version match the twitter ecosystems version has been great. How about replicating that here and moving the version to match the twitter version it's compiled against

**Comment by travisbrown** [comment]
Yes, this is the plan! I've been holding off until iteratee.io 1.0, so that I wouldn't have to line that up with a monthly release, but work on iteratee.io has been going slowly enough that it might make sense just to switch now. There's [some discussion here](https://github.com/travisbrown/iteratee-twitter/releases/tag/v0.18.0), but I'm happy to have an actual issue for this instead—thanks @chris-vale-ck.

**Comment by travisbrown** [comment]
Done in this morning's 18.4.0 release!
